from enum import Enum


class PayloadCategory(str, Enum):
  NANOSATELLITE = "NANOSATELLITE"
  EARTH_OBSERVATION = "EARTH_OBSERVATION"
  METEOROLOGY = "METEOROLOGY"
  TELECOMMUNICATIONS = "TELECOMMUNICATIONS"
  NAVIGATION = "NAVIGATION"
  INTELLIGENCE = "INTELLIGENCE"
  CARGO = "CARGO"
  SCIENTIFIC = "SCIENTIFIC"
  EXPLORATION = "EXPLORATION"
  CREWED = "CREWED"