from enum import Enum


class FlightStatus(str, Enum):
    # Pré-lancement
    INITIALIZING = "INITIALIZING"
    PRE_LAUNCH = "PRE_LAUNCH"
    READY_FOR_LAUNCH = "READY_FOR_LAUNCH"
    # Ascension
    LIFTOFF = "LIFTOFF"
    MAXIMUM_DYNAMIC_PRESSURE = "MAXIMUM_DYNAMIC_PRESSURE"
    MAIN_ENGINE_CUTOFF = "MAIN_ENGINE_CUTOFF"
    STAGE_SEPARATION = "STAGE_SEPARATION"
    FAIRING_JETTISON = "FAIRING_JETTISON"
    SECOND_ENGINE_START = "SECOND_ENGINE_START"
    SECOND_ENGINE_CUTOFF = "SECOND_ENGINE_CUTOFF"
    # Mise en orbite
    COASTING = "COASTING"
    ORBIT_RAISING = "ORBIT_RAISING"
    APOGEE_BURN = "APOGEE_BURN"
    ORBIT_INSERTION = "ORBIT_INSERTION"
    # Post-insertion
    ORBIT_ACHIEVED = "ORBIT_ACHIEVED"
    PAYLOAD_DEPLOYMENT = "PAYLOAD_DEPLOYMENT"
    MISSION_COMPLETE = "MISSION_COMPLETE"
    # Transversaux
    ABORTED = "ABORTED"
    FAILURE = "FAILURE"
    LOST = "LOST"