from enum import Enum


class OrbitType(str, Enum):
    LOW_EARTH_ORBIT = "LOW_EARTH_ORBIT"
    MEDIUM_EARTH_ORBIT = "MEDIUM_EARTH_ORBIT"
    GEOSTATIONARY_ORBIT = "GEOSTATIONARY_ORBIT"
    GEOSYNCHRONOUS_ORBIT = "GEOSYNCHRONOUS_ORBIT"
    SUN_SYNCHRONOUS_ORBIT = "SUN_SYNCHRONOUS_ORBIT"
    HIGHLY_ELLIPTICAL_ORBIT = "HIGHLY_ELLIPTICAL_ORBIT"
    TRANS_LUNAR_INJECTION = "TRANS_LUNAR_INJECTION"
    LUNAR_ORBIT = "LUNAR_ORBIT"